# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fomin/Рабочий стол/Курсовая работа /documents.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(803, 650)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(301, 0, 244, 50))
        self.label_3.setStyleSheet(" font-size:28pt; color:rgb(243, 202, 32);")
        self.label_3.setObjectName("label_3")
        self.typdoc_2 = QtWidgets.QComboBox(Dialog)
        self.typdoc_2.setGeometry(QtCore.QRect(557, 200, 210, 32))
        self.typdoc_2.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.typdoc_2.setObjectName("typdoc_2")
        self.whattext = QtWidgets.QLineEdit(Dialog)
        self.whattext.setGeometry(QtCore.QRect(556, 239, 210, 32))
        self.whattext.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(34, 34, 34);\n"
"color:rgb(243, 202, 32);")
        self.whattext.setText("")
        self.whattext.setObjectName("whattext")
        self.what = QtWidgets.QPushButton(Dialog)
        self.what.setGeometry(QtCore.QRect(635, 281, 72, 31))
        self.what.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.what.setObjectName("what")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(628, 158, 78, 32))
        self.label_9.setMinimumSize(QtCore.QSize(68, 32))
        self.label_9.setStyleSheet(" font-size:15pt; font-weight:600; color:#f3ca20;\n"
"")
        self.label_9.setObjectName("label_9")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(46, 58, 487, 262))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet(" font-size:15pt; color:#f3ca20;font-weight:600;\n"
"")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet(" font-size:15pt; color:#f3ca20;font-weight:600;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.datestart = QtWidgets.QDateEdit(self.layoutWidget)
        self.datestart.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.datestart.setObjectName("datestart")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.datestart)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);font-weight:600;")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);font-weight:600;")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.typdoc = QtWidgets.QComboBox(self.layoutWidget)
        self.typdoc.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.typdoc.setObjectName("typdoc")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.typdoc)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);font-weight:600;")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.statusdoc = QtWidgets.QComboBox(self.layoutWidget)
        self.statusdoc.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.statusdoc.setObjectName("statusdoc")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.statusdoc)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);font-weight:600;")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.datefinish = QtWidgets.QDateEdit(self.layoutWidget)
        self.datefinish.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.datefinish.setObjectName("datefinish")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.datefinish)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);font-weight:600;")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comm = QtWidgets.QLineEdit(self.layoutWidget)
        self.comm.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.comm.setObjectName("comm")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comm)
        self.namber = QtWidgets.QLineEdit(self.layoutWidget)
        self.namber.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.namber.setText("")
        self.namber.setObjectName("namber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.namber)
        self.author = QtWidgets.QComboBox(self.layoutWidget)
        self.author.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(243, 202, 32);\n"
"color: rgb(0, 0, 0)")
        self.author.setObjectName("author")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.author)
        self.twStaffs = QtWidgets.QTableWidget(Dialog)
        self.twStaffs.setGeometry(QtCore.QRect(43, 324, 726, 273))
        self.twStaffs.setStyleSheet("font-size:15pt; \n"
"color:rgb(243, 202, 32);\n"
"background-color: rgb(34, 34, 34);")
        self.twStaffs.setObjectName("twStaffs")
        self.twStaffs.setColumnCount(0)
        self.twStaffs.setRowCount(0)
        self.apdate = QtWidgets.QPushButton(Dialog)
        self.apdate.setGeometry(QtCore.QRect(660, 66, 104, 31))
        self.apdate.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.apdate.setObjectName("apdate")
        self.open = QtWidgets.QPushButton(Dialog)
        self.open.setGeometry(QtCore.QRect(559, 66, 95, 31))
        self.open.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt;  color: rgb(0, 0, 0)")
        self.open.setObjectName("open")
        self.dell = QtWidgets.QPushButton(Dialog)
        self.dell.setGeometry(QtCore.QRect(559, 103, 96, 31))
        self.dell.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.dell.setObjectName("dell")
        self.what_5 = QtWidgets.QPushButton(Dialog)
        self.what_5.setGeometry(QtCore.QRect(660, 103, 106, 31))
        self.what_5.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt;  color: rgb(0, 0, 0)")
        self.what_5.setObjectName("what_5")
        self.what_2 = QtWidgets.QPushButton(Dialog)
        self.what_2.setGeometry(QtCore.QRect(126, 606, 141, 31))
        self.what_2.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.what_2.setObjectName("what_2")
        self.what_3 = QtWidgets.QPushButton(Dialog)
        self.what_3.setGeometry(QtCore.QRect(268, 606, 141, 31))
        self.what_3.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.what_3.setObjectName("what_3")
        self.what_4 = QtWidgets.QPushButton(Dialog)
        self.what_4.setGeometry(QtCore.QRect(410, 606, 141, 31))
        self.what_4.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.what_4.setObjectName("what_4")
        self.what_6 = QtWidgets.QPushButton(Dialog)
        self.what_6.setGeometry(QtCore.QRect(552, 606, 141, 31))
        self.what_6.setStyleSheet("background-color: rgb(243, 202, 32);\n"
"font-size:14pt; color: rgb(0, 0, 0)")
        self.what_6.setObjectName("what_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Документы</span></p></body></html>"))
        self.what.setText(_translate("Dialog", "Найти"))
        self.label_9.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Поиск</span></p></body></html>"))
        self.label_9.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#f3ca20;\">Поиск</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "Поиск"))
        self.label.setText(_translate("Dialog", "Номер документа"))
        self.label_2.setText(_translate("Dialog", "Дата создания"))
        self.label_4.setText(_translate("Dialog", "Автор"))
        self.label_5.setText(_translate("Dialog", "Тип документа"))
        self.label_6.setText(_translate("Dialog", "Статус документа"))
        self.label_7.setText(_translate("Dialog", "Дата выполнения"))
        self.label_8.setText(_translate("Dialog", "Комментарий"))
        self.apdate.setText(_translate("Dialog", "Добавить"))
        self.open.setText(_translate("Dialog", "Открыть"))
        self.dell.setText(_translate("Dialog", "Удалить"))
        self.what_5.setText(_translate("Dialog", "Изменить"))
        self.what_2.setText(_translate("Dialog", "Сотрудники"))
        self.what_3.setText(_translate("Dialog", "Отделы"))
        self.what_4.setText(_translate("Dialog", "Исполнители"))
        self.what_6.setText(_translate("Dialog", "Связанные"))
